version: '3.8'
services:
  exchat_web:
    image: exchat_web:0.1.0
    environment:
      - SECRET_KEY_BASE=pXDFtyzYZVjxsHyPf9K72GYRGhBojderEvyA/0usF16GNLe+mTfaKWL+mndQil8c
      - DATABASE_URL=ecto://postgres:postgres@172.17.1.8/exchat_dev
      - RELEASE_DISTRIBUTION=sname
      - RELEASE_NODE=exchat_web
    command: top
