import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :exchat_web, ExchatWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 4000],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
config :exchat, Exchat.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "postgres",
  database: "exchat_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :message, Message.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "postgres",
  database: "message_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10
